"""Schema PostgreSQL di QUANTO: migrazioni numerate, applicate una sola volta e in ordine.

Regole:
- una migrazione già pubblicata non si modifica mai: si aggiunge la successiva;
- le date restano testo ISO-8601 (ordinabili come stringhe) e i contenuti strutturati JSON in colonne TEXT: così il
  registro firmato e le impronte non dipendono dal formato di serializzazione del database;
- i file (PDF, pagine) stanno in colonne BYTEA.
"""
from __future__ import annotations

from typing import List, Tuple

_INIT = """
CREATE TABLE anchors (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_key TEXT NOT NULL UNIQUE,
    merkle_root TEXT NOT NULL,
    registered_at TEXT NOT NULL,
    prev_hash TEXT NOT NULL,
    entry_hash TEXT NOT NULL,
    key_id TEXT NOT NULL,
    public_key TEXT NOT NULL,
    signature TEXT NOT NULL
);

-- Il registro è append-only anche a livello di database: nessuna UPDATE o DELETE (le si può fare solo
-- disattivando esplicitamente il trigger, cosa che lascia comunque la catena di hash spezzata e rilevabile).
CREATE FUNCTION quanto_anchors_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'anchors è append-only: % non consentito', TG_OP USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER anchors_no_update_delete BEFORE UPDATE OR DELETE ON anchors
    FOR EACH ROW EXECUTE FUNCTION quanto_anchors_append_only();
CREATE TRIGGER anchors_no_truncate BEFORE TRUNCATE ON anchors
    FOR EACH STATEMENT EXECUTE FUNCTION quanto_anchors_append_only();

CREATE TABLE bandi (
    bando_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    issuer TEXT,
    deadline TEXT,
    source_url TEXT,
    catalog_status TEXT NOT NULL DEFAULT 'CATALOGED',
    extraction_status TEXT NOT NULL DEFAULT 'NOT_STARTED',
    requested_by_clients INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TEXT NOT NULL,
    op TEXT NOT NULL,
    status TEXT NOT NULL,
    actor TEXT NOT NULL,
    project_id TEXT,
    bando_id TEXT,
    duration_ms DOUBLE PRECISION,
    summary TEXT NOT NULL,
    details TEXT,
    run_id BIGINT
);
CREATE INDEX idx_events_op ON events (op);
CREATE INDEX idx_events_project ON events (project_id);

CREATE TABLE runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TEXT NOT NULL,
    kind TEXT NOT NULL,                -- VALIDATE | ALLOCATION
    project_id TEXT,
    bando_id TEXT,
    merkle_root TEXT,
    request_json TEXT NOT NULL,
    response_json TEXT NOT NULL
);
CREATE INDEX idx_runs_bando ON runs (bando_id, kind);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TEXT NOT NULL,
    kind TEXT NOT NULL,
    name TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    size_bytes BIGINT NOT NULL,
    bando_id TEXT,
    project_id TEXT,
    meta TEXT
);

CREATE TABLE bando_meta (
    bando_id TEXT PRIMARY KEY,
    meta TEXT NOT NULL
);

CREATE TABLE requirements (
    bando_id TEXT NOT NULL,
    seq INTEGER NOT NULL,
    topic TEXT NOT NULL,
    kind TEXT NOT NULL,
    text TEXT NOT NULL,
    criteria TEXT NOT NULL,
    source_ref TEXT,
    origin TEXT NOT NULL,
    PRIMARY KEY (bando_id, seq)
);

CREATE TABLE bando_sources (
    bando_id TEXT NOT NULL,
    ts TEXT NOT NULL,
    name TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    text TEXT NOT NULL,
    url TEXT,
    tier TEXT,
    content_type TEXT,
    pages INTEGER,
    origin TEXT,
    file_sha256 TEXT,
    analysis TEXT,
    warnings TEXT,
    PRIMARY KEY (bando_id, sha256)
);

CREATE TABLE bando_files (
    bando_id TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    ts TEXT NOT NULL,
    name TEXT NOT NULL,
    content_type TEXT,
    size_bytes BIGINT NOT NULL,
    data BYTEA NOT NULL,
    PRIMARY KEY (bando_id, sha256)
);

CREATE TABLE bando_tombstones (
    bando_id TEXT PRIMARY KEY,
    ts TEXT NOT NULL
);

CREATE TABLE rules (
    bando_id TEXT NOT NULL,
    rule_key TEXT NOT NULL,
    value TEXT,
    origin TEXT NOT NULL,
    status TEXT NOT NULL,
    passes TEXT,
    source_ref TEXT,
    PRIMARY KEY (bando_id, rule_key)
);
"""

# (versione, nome, SQL). Aggiungere in coda, mai modificare le esistenti.
MIGRATIONS: List[Tuple[int, str, str]] = [
    (1, "init", _INIT),
]
