"""Schema PostgreSQL di QUANTO: migrazioni numerate, applicate una sola volta e in ordine.

Regole:
- una migrazione già pubblicata non si modifica mai: si aggiunge la successiva;
- le date restano testo ISO-8601 (ordinabili come stringhe) e i contenuti strutturati JSON in colonne TEXT: così il
  registro firmato e le impronte non dipendono dal formato di serializzazione del database;
- i file (PDF, pagine) stanno in colonne BYTEA.
"""
from __future__ import annotations

from typing import List, Tuple

_INIT = """
CREATE TABLE anchors (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_key TEXT NOT NULL UNIQUE,
    merkle_root TEXT NOT NULL,
    registered_at TEXT NOT NULL,
    prev_hash TEXT NOT NULL,
    entry_hash TEXT NOT NULL,
    key_id TEXT NOT NULL,
    public_key TEXT NOT NULL,
    signature TEXT NOT NULL
);

-- Il registro è append-only anche a livello di database: nessuna UPDATE o DELETE (le si può fare solo
-- disattivando esplicitamente il trigger, cosa che lascia comunque la catena di hash spezzata e rilevabile).
CREATE FUNCTION quanto_anchors_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'anchors è append-only: % non consentito', TG_OP USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER anchors_no_update_delete BEFORE UPDATE OR DELETE ON anchors
    FOR EACH ROW EXECUTE FUNCTION quanto_anchors_append_only();
CREATE TRIGGER anchors_no_truncate BEFORE TRUNCATE ON anchors
    FOR EACH STATEMENT EXECUTE FUNCTION quanto_anchors_append_only();

CREATE TABLE bandi (
    bando_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    issuer TEXT,
    deadline TEXT,
    source_url TEXT,
    catalog_status TEXT NOT NULL DEFAULT 'CATALOGED',
    extraction_status TEXT NOT NULL DEFAULT 'NOT_STARTED',
    requested_by_clients INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TEXT NOT NULL,
    op TEXT NOT NULL,
    status TEXT NOT NULL,
    actor TEXT NOT NULL,
    project_id TEXT,
    bando_id TEXT,
    duration_ms DOUBLE PRECISION,
    summary TEXT NOT NULL,
    details TEXT,
    run_id BIGINT
);
CREATE INDEX idx_events_op ON events (op);
CREATE INDEX idx_events_project ON events (project_id);

CREATE TABLE runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TEXT NOT NULL,
    kind TEXT NOT NULL,                -- VALIDATE | ALLOCATION
    project_id TEXT,
    bando_id TEXT,
    merkle_root TEXT,
    request_json TEXT NOT NULL,
    response_json TEXT NOT NULL
);
CREATE INDEX idx_runs_bando ON runs (bando_id, kind);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TEXT NOT NULL,
    kind TEXT NOT NULL,
    name TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    size_bytes BIGINT NOT NULL,
    bando_id TEXT,
    project_id TEXT,
    meta TEXT
);

CREATE TABLE bando_meta (
    bando_id TEXT PRIMARY KEY,
    meta TEXT NOT NULL
);

CREATE TABLE requirements (
    bando_id TEXT NOT NULL,
    seq INTEGER NOT NULL,
    topic TEXT NOT NULL,
    kind TEXT NOT NULL,
    text TEXT NOT NULL,
    criteria TEXT NOT NULL,
    source_ref TEXT,
    origin TEXT NOT NULL,
    PRIMARY KEY (bando_id, seq)
);

CREATE TABLE bando_sources (
    bando_id TEXT NOT NULL,
    ts TEXT NOT NULL,
    name TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    text TEXT NOT NULL,
    url TEXT,
    tier TEXT,
    content_type TEXT,
    pages INTEGER,
    origin TEXT,
    file_sha256 TEXT,
    analysis TEXT,
    warnings TEXT,
    PRIMARY KEY (bando_id, sha256)
);

CREATE TABLE bando_files (
    bando_id TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    ts TEXT NOT NULL,
    name TEXT NOT NULL,
    content_type TEXT,
    size_bytes BIGINT NOT NULL,
    data BYTEA NOT NULL,
    PRIMARY KEY (bando_id, sha256)
);

CREATE TABLE bando_tombstones (
    bando_id TEXT PRIMARY KEY,
    ts TEXT NOT NULL
);

CREATE TABLE rules (
    bando_id TEXT NOT NULL,
    rule_key TEXT NOT NULL,
    value TEXT,
    origin TEXT NOT NULL,
    status TEXT NOT NULL,
    passes TEXT,
    source_ref TEXT,
    PRIMARY KEY (bando_id, rule_key)
);
"""

_FONTE_B = """
-- Fonte B: tabelle ufficiali versionate per data di validità (Modulo 9.2). Nessun valore è scritto nel codice.
CREATE TABLE fonte_b_datasets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL CHECK (kind IN ('CCNL', 'PARAMS', 'AMORTIZATION', 'BENCHMARK')),
    code TEXT NOT NULL,                                 -- CCNL: sigla del contratto; altri tipi: nome breve dell'insieme
    name TEXT NOT NULL,
    version TEXT NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE,
    status TEXT NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED', 'SUPERSEDED')),
    official BOOLEAN NOT NULL DEFAULT FALSE,            -- il manager attesta che i valori sono quelli della fonte indicata
    source_name TEXT NOT NULL,
    source_url TEXT,
    source_ref TEXT,
    file_name TEXT,
    file_sha256 TEXT,
    file_data BYTEA,
    notes TEXT,
    created_by TEXT NOT NULL,
    created_at TEXT NOT NULL,
    published_by TEXT,
    published_at TEXT,
    UNIQUE (kind, code, version),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);
CREATE TABLE fonte_b_ccnl (
    dataset_id BIGINT NOT NULL REFERENCES fonte_b_datasets (id) ON DELETE CASCADE,
    level TEXT NOT NULL,
    standard_hours INTEGER NOT NULL CHECK (standard_hours > 0),
    social_charges_pct NUMERIC(7, 4) NOT NULL CHECK (social_charges_pct >= 0 AND social_charges_pct < 1),
    tfr_pct NUMERIC(7, 4) NOT NULL CHECK (tfr_pct >= 0 AND tfr_pct < 1),
    PRIMARY KEY (dataset_id, level)
);
CREATE TABLE fonte_b_params (
    dataset_id BIGINT NOT NULL REFERENCES fonte_b_datasets (id) ON DELETE CASCADE,
    param_key TEXT NOT NULL,
    value NUMERIC(18, 6) NOT NULL,
    unit TEXT,
    PRIMARY KEY (dataset_id, param_key)
);
CREATE TABLE fonte_b_amort (
    dataset_id BIGINT NOT NULL REFERENCES fonte_b_datasets (id) ON DELETE CASCADE,
    category_code TEXT NOT NULL,
    description TEXT,
    rate_pct NUMERIC(7, 4) NOT NULL CHECK (rate_pct > 0 AND rate_pct <= 1),
    PRIMARY KEY (dataset_id, category_code)
);
CREATE TABLE fonte_b_benchmarks (
    dataset_id BIGINT NOT NULL REFERENCES fonte_b_datasets (id) ON DELETE CASCADE,
    bench_kind TEXT NOT NULL CHECK (bench_kind IN ('PRICE', 'DAILY_RATE')),
    category_code TEXT NOT NULL,
    description TEXT,
    reference_eur NUMERIC(18, 2) NOT NULL CHECK (reference_eur > 0),
    PRIMARY KEY (dataset_id, bench_kind, category_code)
);
"""

_FONTE_C = """
-- Fonte C: documenti contabili del cliente (buste paga, bilanci, F24). Il file è cifrato a riposo (AES-256-GCM); nei campi
-- estratti i dati personali (nomi, codici fiscali, IBAN) esistono solo come token opachi (Modulo 16).
CREATE TABLE client_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_type TEXT NOT NULL CHECK (doc_type IN ('PAYSLIP', 'BALANCE_SHEET', 'F24')),
    filename TEXT NOT NULL,
    content_type TEXT,
    size_bytes BIGINT NOT NULL,
    sha256 TEXT NOT NULL,
    data_enc BYTEA NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('PARSED', 'NEEDS_REVIEW', 'CONFIRMED', 'FAILED')),
    method TEXT,                                   -- TEXT_LAYER | OCR:<motore>
    pages INTEGER,
    mean_confidence NUMERIC(5, 4),
    error TEXT,
    owner TEXT NOT NULL,
    created_at TEXT NOT NULL
);
CREATE INDEX idx_client_documents_owner ON client_documents (owner);
CREATE TABLE client_document_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES client_documents (id) ON DELETE CASCADE,
    field_key TEXT NOT NULL,
    value TEXT,                                    -- testo o JSON (righe di bilancio / F24)
    confidence NUMERIC(5, 4) NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('AUTO', 'NEEDS_REVIEW', 'CONFIRMED', 'CORRECTED')),
    pii BOOLEAN NOT NULL DEFAULT FALSE,
    page INTEGER,
    snippet TEXT,                                  -- riga di origine ripulita dai dati personali
    reviewed_by TEXT,
    reviewed_at TEXT
);
CREATE INDEX idx_client_fields_doc ON client_document_fields (document_id);
"""

_FUNDS = """
-- Linee di finanziamento per l'allocazione annuale: ricavate dai bandi (Fonte A) o indicate da una persona.
CREATE TABLE funding_lines (
    fund_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    bando_id TEXT,
    allowed_categories TEXT NOT NULL,              -- JSON
    coverage_pct NUMERIC(7, 4) NOT NULL CHECK (coverage_pct > 0 AND coverage_pct <= 1),
    category_coverage_pct TEXT,                    -- JSON
    max_total_eur NUMERIC(18, 2) CHECK (max_total_eur IS NULL OR max_total_eur > 0),
    category_max_share TEXT,                       -- JSON
    de_minimis BOOLEAN NOT NULL DEFAULT FALSE,
    excludes TEXT,                                 -- JSON
    active_from_month INTEGER NOT NULL DEFAULT 1 CHECK (active_from_month BETWEEN 1 AND 12),
    active_to_month INTEGER NOT NULL DEFAULT 12 CHECK (active_to_month BETWEEN 1 AND 12),
    source_ref TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_by TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
"""

_USERS = """
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE CHECK (email = lower(email)),
    name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('USER', 'MANAGER')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    token_version INTEGER NOT NULL DEFAULT 1,
    failed_logins INTEGER NOT NULL DEFAULT 0,
    locked_until TEXT,
    created_at TEXT NOT NULL,
    last_login_at TEXT
);
"""

_PATTERN = """
-- Banca dati dei pattern vincenti (Modulo 5): budget storici importati con la loro fonte; archetipi calcolati con k-means (Modulo 6).
CREATE TABLE pattern_budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bando_category TEXT NOT NULL,
    source TEXT NOT NULL,
    source_url TEXT,
    year INTEGER,
    total_eur NUMERIC(18, 2),
    score NUMERIC(8, 2),
    personnel_pct NUMERIC(8, 6) NOT NULL, assets_pct NUMERIC(8, 6) NOT NULL, consulting_pct NUMERIC(8, 6) NOT NULL,
    overhead_pct NUMERIC(8, 6) NOT NULL, training_pct NUMERIC(8, 6) NOT NULL, communication_pct NUMERIC(8, 6) NOT NULL,
    created_by TEXT NOT NULL,
    created_at TEXT NOT NULL,
    CHECK (abs(personnel_pct + assets_pct + consulting_pct + overhead_pct + training_pct + communication_pct - 1) <= 0.02)
);
CREATE INDEX idx_pattern_budgets_cat ON pattern_budgets (bando_category);
CREATE TABLE pattern_archetypes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bando_category TEXT NOT NULL,
    label TEXT NOT NULL,
    centroid TEXT NOT NULL,
    members INTEGER NOT NULL,
    score_min NUMERIC(8, 2),
    score_max NUMERIC(8, 2),
    method TEXT NOT NULL,
    computed_at TEXT NOT NULL,
    UNIQUE (bando_category, label)
);
"""

_DRAFT_DOC_TYPE = """
ALTER TABLE client_documents DROP CONSTRAINT client_documents_doc_type_check;
ALTER TABLE client_documents ADD CONSTRAINT client_documents_doc_type_check CHECK (doc_type IN ('PAYSLIP', 'BALANCE_SHEET', 'F24', 'APPLICATION_DRAFT'));
"""

# Supabase espone di serie ogni tabella dello schema "public" tramite PostgREST (l'API REST automatica, raggiungibile
# con la chiave "anon"): senza RLS, chiunque avesse quella chiave potrebbe leggere/scrivere queste tabelle bypassando
# del tutto login e permessi del backend. Nessuna funzione di QUANTO passa da PostgREST (il backend si collega
# direttamente a Postgres con QUANTO_DATABASE_URL, con un ruolo che ha BYPASSRLS e quindi ignora questo blocco): qui
# si chiude solo quella porta secondaria, senza policy permissive perché non deve passare nessuno tranne il backend.
_ENABLE_RLS = """
ALTER TABLE anchors ENABLE ROW LEVEL SECURITY;
ALTER TABLE schema_migrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE bandi ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE bando_meta ENABLE ROW LEVEL SECURITY;
ALTER TABLE requirements ENABLE ROW LEVEL SECURITY;
ALTER TABLE bando_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE bando_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE bando_tombstones ENABLE ROW LEVEL SECURITY;
ALTER TABLE rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE fonte_b_datasets ENABLE ROW LEVEL SECURITY;
ALTER TABLE fonte_b_ccnl ENABLE ROW LEVEL SECURITY;
ALTER TABLE fonte_b_params ENABLE ROW LEVEL SECURITY;
ALTER TABLE fonte_b_amort ENABLE ROW LEVEL SECURITY;
ALTER TABLE fonte_b_benchmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_document_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE funding_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE pattern_budgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE pattern_archetypes ENABLE ROW LEVEL SECURITY;
"""

_REQUIREMENT_FIGURES = """
ALTER TABLE requirements ADD COLUMN figures TEXT;
"""

_COMPANY_PROFILE = """
-- Profilo aziendale: i dati dell'impresa che si ricavano dai suoi documenti o si inseriscono a mano. Un profilo per utente.
CREATE TABLE company_profiles (
    owner TEXT PRIMARY KEY,
    data TEXT NOT NULL,
    sources TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
-- Dati di bilancio per esercizio (ricavi, costi per categoria, dipendenti), con l'origine di ogni valore (documento o inserito a mano).
CREATE TABLE company_financials (
    owner TEXT NOT NULL,
    fiscal_year INTEGER NOT NULL,
    data TEXT NOT NULL,
    sources TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (owner, fiscal_year)
);
ALTER TABLE company_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_financials ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_documents DROP CONSTRAINT client_documents_doc_type_check;
ALTER TABLE client_documents ADD CONSTRAINT client_documents_doc_type_check CHECK (doc_type IN ('PAYSLIP', 'BALANCE_SHEET', 'F24', 'APPLICATION_DRAFT', 'COMPANY_REGISTRY', 'OTHER'));
ALTER TABLE client_documents DROP CONSTRAINT client_documents_status_check;
ALTER TABLE client_documents ADD CONSTRAINT client_documents_status_check CHECK (status IN ('PARSED', 'NEEDS_REVIEW', 'CONFIRMED', 'FAILED', 'STORED'));
"""

# (versione, nome, SQL). Aggiungere in coda, mai modificare le esistenti.
_CATALOG_META = """
-- Scheda di ogni voce del catalogo: descrizione breve e caratteristiche lette dalla pagina ufficiale (mai scritte da un modello).
ALTER TABLE bandi ADD COLUMN summary TEXT;
ALTER TABLE bandi ADD COLUMN catalog_meta TEXT;                 -- JSON: forma di agevolazione, costi ammessi, dimensione, regioni, ATECO, date…
ALTER TABLE bandi ADD COLUMN meta_at TEXT;
"""

_FORECAST_TEMPLATE = """
-- Modello di previsione dell'utente (commercialista, CFO...): variazione annua in percentuale per ogni categoria di spesa e per i ricavi.
CREATE TABLE forecast_templates (
    owner TEXT PRIMARY KEY,
    growth TEXT NOT NULL,
    label TEXT NOT NULL DEFAULT '',
    note TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL
);
ALTER TABLE forecast_templates ENABLE ROW LEVEL SECURITY;
"""

_RETIRE_DEMO = """
-- Tolti dall'applicazione lo scenario demo e il bando di prova: si eliminano anche le tracce che avevano lasciato (bando, regole, eventi, esecuzioni).
DELETE FROM events WHERE op = 'budget.demo' OR bando_id = 'QUANTO-SANDBOX-60' OR project_id IN ('DEMO-SHAPE', 'PRJ-DEMO-COMPLETO', 'PRJ-DEMO-REALISTICO');
DELETE FROM runs WHERE bando_id = 'QUANTO-SANDBOX-60' OR project_id IN ('DEMO-SHAPE', 'PRJ-DEMO-COMPLETO', 'PRJ-DEMO-REALISTICO');
DELETE FROM documents WHERE bando_id = 'QUANTO-SANDBOX-60' OR project_id IN ('DEMO-SHAPE', 'PRJ-DEMO-COMPLETO', 'PRJ-DEMO-REALISTICO');
DELETE FROM funding_lines WHERE bando_id = 'QUANTO-SANDBOX-60';
DELETE FROM bando_files WHERE bando_id = 'QUANTO-SANDBOX-60';
DELETE FROM bando_sources WHERE bando_id = 'QUANTO-SANDBOX-60';
DELETE FROM requirements WHERE bando_id = 'QUANTO-SANDBOX-60';
DELETE FROM rules WHERE bando_id = 'QUANTO-SANDBOX-60';
DELETE FROM bando_meta WHERE bando_id = 'QUANTO-SANDBOX-60';
DELETE FROM bandi WHERE bando_id = 'QUANTO-SANDBOX-60';
"""

_BUDGET_TEMPLATES = """
-- Template di budget: per una nicchia (ATECO) che ha scelto un bando, come è ripartito il budget del progetto e com'è andata. Allenano il consiglio del Confronto.
CREATE TABLE budget_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner TEXT NOT NULL,
    shared BOOLEAN NOT NULL DEFAULT FALSE,
    ateco_code TEXT NOT NULL,
    ateco_division TEXT NOT NULL,
    ateco_section TEXT NOT NULL,
    company_size TEXT,
    region TEXT,
    bando_id TEXT NOT NULL,
    bando_name TEXT NOT NULL,
    total_eur NUMERIC(18, 2),
    shares TEXT NOT NULL,
    outcome TEXT NOT NULL DEFAULT 'BOZZA' CHECK (outcome IN ('BOZZA', 'PRESENTATO', 'AMMESSO', 'NON_AMMESSO')),
    score NUMERIC(8, 2),
    note TEXT NOT NULL DEFAULT '',
    recommended TEXT,
    distance NUMERIC(8, 4),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE INDEX idx_templates_bando ON budget_templates (bando_id);
CREATE INDEX idx_templates_division ON budget_templates (ateco_division);
ALTER TABLE budget_templates ENABLE ROW LEVEL SECURITY;
"""

CLIENTS_DATA_MIGRATION = """
-- I dati d'impresa di ogni utente diventano il suo primo «lavoro»: chiave <utente>#<id del lavoro>.
INSERT INTO clients (owner, name, note, created_at)
SELECT o.owner, COALESCE(NULLIF(p.data::json->>'legal_name', ''), 'Prima azienda'), '', to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
FROM (SELECT owner FROM company_profiles UNION SELECT owner FROM company_financials UNION SELECT owner FROM client_documents UNION SELECT owner FROM forecast_templates) o
LEFT JOIN company_profiles p ON p.owner = o.owner
WHERE o.owner NOT LIKE '%#%';
UPDATE company_profiles t SET owner = t.owner || '#' || c.id FROM clients c WHERE c.owner = t.owner AND t.owner NOT LIKE '%#%';
UPDATE company_financials t SET owner = t.owner || '#' || c.id FROM clients c WHERE c.owner = t.owner AND t.owner NOT LIKE '%#%';
UPDATE client_documents t SET owner = t.owner || '#' || c.id FROM clients c WHERE c.owner = t.owner AND t.owner NOT LIKE '%#%';
UPDATE forecast_templates t SET owner = t.owner || '#' || c.id FROM clients c WHERE c.owner = t.owner AND t.owner NOT LIKE '%#%';
"""

_CLIENTS = """
-- Lo studio e i suoi lavori: ogni azienda cliente ha profilo, bilanci, documenti e risultati propri.
CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner TEXT NOT NULL,
    name TEXT NOT NULL,
    note TEXT NOT NULL DEFAULT '',
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL
);
CREATE INDEX idx_clients_owner ON clients (owner);
CREATE TABLE client_state (
    scope TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (scope, key)
);
ALTER TABLE budget_templates ADD COLUMN client_id BIGINT;
UPDATE budget_templates SET shared = TRUE;                         -- i template alimentano sempre il motore collettivo (in forma anonima)
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_state ENABLE ROW LEVEL SECURITY;
""" + CLIENTS_DATA_MIGRATION

_USER_PROFILE = """
-- Dati dello studio sul profilo dell'utente.
ALTER TABLE users ADD COLUMN studio_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN studio_vat TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN phone TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN job_title TEXT NOT NULL DEFAULT '';
"""

MIGRATIONS: List[Tuple[int, str, str]] = [
    (1, "init", _INIT),
    (2, "fonte_b", _FONTE_B),
    (3, "fonte_c", _FONTE_C),
    (4, "funding_lines", _FUNDS),
    (5, "users", _USERS),
    (6, "pattern", _PATTERN),
    (7, "draft_doc_type", _DRAFT_DOC_TYPE),
    (8, "enable_rls", _ENABLE_RLS),
    (9, "requirement_figures", _REQUIREMENT_FIGURES),
    (10, "company_profile", _COMPANY_PROFILE),
    (11, "catalog_meta", _CATALOG_META),
    (12, "forecast_template", _FORECAST_TEMPLATE),
    (13, "retire_demo", _RETIRE_DEMO),
    (14, "budget_templates", _BUDGET_TEMPLATES),
    (15, "clients", _CLIENTS),
    (16, "user_profile", _USER_PROFILE),
]
