"""Schema PostgreSQL di QUANTO: migrazioni numerate, applicate una sola volta e in ordine.

Regole:
- una migrazione già pubblicata non si modifica mai: si aggiunge la successiva;
- le date restano testo ISO-8601 (ordinabili come stringhe) e i contenuti strutturati JSON in colonne TEXT: così il
  registro firmato e le impronte non dipendono dal formato di serializzazione del database;
- i file (PDF, pagine) stanno in colonne BYTEA.
"""
from __future__ import annotations

from typing import List, Tuple

_INIT = """
CREATE TABLE anchors (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_key TEXT NOT NULL UNIQUE,
    merkle_root TEXT NOT NULL,
    registered_at TEXT NOT NULL,
    prev_hash TEXT NOT NULL,
    entry_hash TEXT NOT NULL,
    key_id TEXT NOT NULL,
    public_key TEXT NOT NULL,
    signature TEXT NOT NULL
);

-- Il registro è append-only anche a livello di database: nessuna UPDATE o DELETE (le si può fare solo
-- disattivando esplicitamente il trigger, cosa che lascia comunque la catena di hash spezzata e rilevabile).
CREATE FUNCTION quanto_anchors_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'anchors è append-only: % non consentito', TG_OP USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER anchors_no_update_delete BEFORE UPDATE OR DELETE ON anchors
    FOR EACH ROW EXECUTE FUNCTION quanto_anchors_append_only();
CREATE TRIGGER anchors_no_truncate BEFORE TRUNCATE ON anchors
    FOR EACH STATEMENT EXECUTE FUNCTION quanto_anchors_append_only();

CREATE TABLE bandi (
    bando_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    issuer TEXT,
    deadline TEXT,
    source_url TEXT,
    catalog_status TEXT NOT NULL DEFAULT 'CATALOGED',
    extraction_status TEXT NOT NULL DEFAULT 'NOT_STARTED',
    requested_by_clients INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TEXT NOT NULL,
    op TEXT NOT NULL,
    status TEXT NOT NULL,
    actor TEXT NOT NULL,
    project_id TEXT,
    bando_id TEXT,
    duration_ms DOUBLE PRECISION,
    summary TEXT NOT NULL,
    details TEXT,
    run_id BIGINT
);
CREATE INDEX idx_events_op ON events (op);
CREATE INDEX idx_events_project ON events (project_id);

CREATE TABLE runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TEXT NOT NULL,
    kind TEXT NOT NULL,                -- VALIDATE | ALLOCATION
    project_id TEXT,
    bando_id TEXT,
    merkle_root TEXT,
    request_json TEXT NOT NULL,
    response_json TEXT NOT NULL
);
CREATE INDEX idx_runs_bando ON runs (bando_id, kind);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TEXT NOT NULL,
    kind TEXT NOT NULL,
    name TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    size_bytes BIGINT NOT NULL,
    bando_id TEXT,
    project_id TEXT,
    meta TEXT
);

CREATE TABLE bando_meta (
    bando_id TEXT PRIMARY KEY,
    meta TEXT NOT NULL
);

CREATE TABLE requirements (
    bando_id TEXT NOT NULL,
    seq INTEGER NOT NULL,
    topic TEXT NOT NULL,
    kind TEXT NOT NULL,
    text TEXT NOT NULL,
    criteria TEXT NOT NULL,
    source_ref TEXT,
    origin TEXT NOT NULL,
    PRIMARY KEY (bando_id, seq)
);

CREATE TABLE bando_sources (
    bando_id TEXT NOT NULL,
    ts TEXT NOT NULL,
    name TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    text TEXT NOT NULL,
    url TEXT,
    tier TEXT,
    content_type TEXT,
    pages INTEGER,
    origin TEXT,
    file_sha256 TEXT,
    analysis TEXT,
    warnings TEXT,
    PRIMARY KEY (bando_id, sha256)
);

CREATE TABLE bando_files (
    bando_id TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    ts TEXT NOT NULL,
    name TEXT NOT NULL,
    content_type TEXT,
    size_bytes BIGINT NOT NULL,
    data BYTEA NOT NULL,
    PRIMARY KEY (bando_id, sha256)
);

CREATE TABLE bando_tombstones (
    bando_id TEXT PRIMARY KEY,
    ts TEXT NOT NULL
);

CREATE TABLE rules (
    bando_id TEXT NOT NULL,
    rule_key TEXT NOT NULL,
    value TEXT,
    origin TEXT NOT NULL,
    status TEXT NOT NULL,
    passes TEXT,
    source_ref TEXT,
    PRIMARY KEY (bando_id, rule_key)
);
"""

_FONTE_B = """
-- Fonte B: tabelle ufficiali versionate per data di validità (Modulo 9.2). Nessun valore è scritto nel codice.
CREATE TABLE fonte_b_datasets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL CHECK (kind IN ('CCNL', 'PARAMS', 'AMORTIZATION', 'BENCHMARK')),
    code TEXT NOT NULL,                                 -- CCNL: sigla del contratto; altri tipi: nome breve dell'insieme
    name TEXT NOT NULL,
    version TEXT NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE,
    status TEXT NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED', 'SUPERSEDED')),
    official BOOLEAN NOT NULL DEFAULT FALSE,            -- il manager attesta che i valori sono quelli della fonte indicata
    source_name TEXT NOT NULL,
    source_url TEXT,
    source_ref TEXT,
    file_name TEXT,
    file_sha256 TEXT,
    file_data BYTEA,
    notes TEXT,
    created_by TEXT NOT NULL,
    created_at TEXT NOT NULL,
    published_by TEXT,
    published_at TEXT,
    UNIQUE (kind, code, version),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);
CREATE TABLE fonte_b_ccnl (
    dataset_id BIGINT NOT NULL REFERENCES fonte_b_datasets (id) ON DELETE CASCADE,
    level TEXT NOT NULL,
    standard_hours INTEGER NOT NULL CHECK (standard_hours > 0),
    social_charges_pct NUMERIC(7, 4) NOT NULL CHECK (social_charges_pct >= 0 AND social_charges_pct < 1),
    tfr_pct NUMERIC(7, 4) NOT NULL CHECK (tfr_pct >= 0 AND tfr_pct < 1),
    PRIMARY KEY (dataset_id, level)
);
CREATE TABLE fonte_b_params (
    dataset_id BIGINT NOT NULL REFERENCES fonte_b_datasets (id) ON DELETE CASCADE,
    param_key TEXT NOT NULL,
    value NUMERIC(18, 6) NOT NULL,
    unit TEXT,
    PRIMARY KEY (dataset_id, param_key)
);
CREATE TABLE fonte_b_amort (
    dataset_id BIGINT NOT NULL REFERENCES fonte_b_datasets (id) ON DELETE CASCADE,
    category_code TEXT NOT NULL,
    description TEXT,
    rate_pct NUMERIC(7, 4) NOT NULL CHECK (rate_pct > 0 AND rate_pct <= 1),
    PRIMARY KEY (dataset_id, category_code)
);
CREATE TABLE fonte_b_benchmarks (
    dataset_id BIGINT NOT NULL REFERENCES fonte_b_datasets (id) ON DELETE CASCADE,
    bench_kind TEXT NOT NULL CHECK (bench_kind IN ('PRICE', 'DAILY_RATE')),
    category_code TEXT NOT NULL,
    description TEXT,
    reference_eur NUMERIC(18, 2) NOT NULL CHECK (reference_eur > 0),
    PRIMARY KEY (dataset_id, bench_kind, category_code)
);
"""

# (versione, nome, SQL). Aggiungere in coda, mai modificare le esistenti.
MIGRATIONS: List[Tuple[int, str, str]] = [
    (1, "init", _INIT),
    (2, "fonte_b", _FONTE_B),
]
